<h1>Cabrera, Ryn Joseph V. BSIT-3A</h1>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import scipy.stats
from scipy.stats import f_oneway

In [2]:
accident = pd.read_csv('dataset\\accident_data.csv')

In [3]:
accident

,Index,Accident_Severity,Accident Date,Latitude,Light_Conditions,District Area,Longitude,Number_of_Casualties,Number_of_Vehicles,Road_Surface_Conditions,Road_Type,Urban_or_Rural_Area,Weather_Conditions,Vehicle_Type
0,200701BS64157,Serious,05/06/2019,51.506187,Darkness - lights lit,Kensington and Chelsea,-0.209082,1,2,Dry,Single carriageway,Urban,Fine no high winds,Car
1,200701BS65737,Serious,02/07/2019,51.495029,Daylight,Kensington and Chelsea,-0.173647,1,2,Wet or damp,Single carriageway,Urban,Raining no high winds,Car
2,200701BS66127,Serious,26/08/2019,51.517715,Darkness - lighting unknown,Kensington and Chelsea,-0.210215,1,3,Dry,NaN,Urban,NaN,Taxi/Private hire car
3,200701BS66128,Serious,16/08/2019,51.495478,Daylight,Kensington and Chelsea,-0.202731,1,4,Dry,Single carriageway,Urban,Fine no high winds,Bus or coach (17 or more pass seats)
4,200701BS66837,Slight,03/09/2019,51.488576,Darkness - lights lit,Kensington and Chelsea,-0.192487,1,2,Dry,NaN,Urban,NaN,Other vehicle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
660674,201091NM01760,Slight,18/02/2022,57.374005,Daylight,Highland,-3.467828,2,1,Dry,Single carriageway,Rural,Fine no high winds,Car
660675,201091NM01881,Slight,21/02/2022,57.232273,Darkness - no lighting,Highland,-3.809281,1,1,Frost or ice,Single carriageway,Rural,Fine no high winds,Car
660676,201091NM01935,Slight,23/02/2022,57.585044,Daylight,Highland,-3.862727,1,3,Frost or ice,Single carriageway,Rural,Fine no high winds,Car
660677,201091NM01964,Serious,23/02/2022,57.214898,Darkness - no lighting,Highland,-3.823997,1,2,Wet or damp,Single carriageway,Rural,Fine no high winds,Motorcycle over 500cc
660678,201091NM02142,Serious,28/02/2022,57.575210,Daylight,Highland,-3.895673,1,1,Wet or damp,Dual carriageway,Rural,Snowing no high winds,Car

In [4]:
accident.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 660679 entries, 0 to 660678
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Index                    660679 non-null  object
 1   Accident_Severity        660679 non-null  object
 2   Accident Date            660679 non-null  object
 3   Latitude                 660654 non-null  float64
 4   Light_Conditions         660679 non-null  object
 5   District Area            660679 non-null  object
 6   Longitude                660653 non-null  float64
 7   Number_of_Casualties     660679 non-null  int64
 8   Number_of_Vehicles       660679 non-null  int64
 9   Road_Surface_Conditions  659953 non-null  object
 10  Road_Type                656159 non-null  object
 11  Urban_or_Rural_Area      660664 non-null  object
 12  Weather_Conditions       646551 non-null  object
 13  Vehicle_Type             660679 non-null  object
dtypes: float64(2), int64(2), object(10)
memory usage: 70.6+ MB

<h1>DROPPING COLUMNS

In [5]:
accident.drop(columns='Index', inplace=True)

In [6]:
accident

,Accident_Severity,Accident Date,Latitude,Light_Conditions,District Area,Longitude,Number_of_Casualties,Number_of_Vehicles,Road_Surface_Conditions,Road_Type,Urban_or_Rural_Area,Weather_Conditions,Vehicle_Type
0,Serious,05/06/2019,51.506187,Darkness - lights lit,Kensington and Chelsea,-0.209082,1,2,Dry,Single carriageway,Urban,Fine no high winds,Car
1,Serious,02/07/2019,51.495029,Daylight,Kensington and Chelsea,-0.173647,1,2,Wet or damp,Single carriageway,Urban,Raining no high winds,Car
2,Serious,26/08/2019,51.517715,Darkness - lighting unknown,Kensington and Chelsea,-0.210215,1,3,Dry,NaN,Urban,NaN,Taxi/Private hire car
3,Serious,16/08/2019,51.495478,Daylight,Kensington and Chelsea,-0.202731,1,4,Dry,Single carriageway,Urban,Fine no high winds,Bus or coach (17 or more pass seats)
4,Slight,03/09/2019,51.488576,Darkness - lights lit,Kensington and Chelsea,-0.192487,1,2,Dry,NaN,Urban,NaN,Other vehicle
...,...,...,...,...,...,...,...,...,...,...,...,...,...
660674,Slight,18/02/2022,57.374005,Daylight,Highland,-3.467828,2,1,Dry,Single carriageway,Rural,Fine no high winds,Car
660675,Slight,21/02/2022,57.232273,Darkness - no lighting,Highland,-3.809281,1,1,Frost or ice,Single carriageway,Rural,Fine no high winds,Car
660676,Slight,23/02/2022,57.585044,Daylight,Highland,-3.862727,1,3,Frost or ice,Single carriageway,Rural,Fine no high winds,Car
660677,Serious,23/02/2022,57.214898,Darkness - no lighting,Highland,-3.823997,1,2,Wet or damp,Single carriageway,Rural,Fine no high winds,Motorcycle over 500cc
660678,Serious,28/02/2022,57.575210,Daylight,Highland,-3.895673,1,1,Wet or damp,Dual carriageway,Rural,Snowing no high winds,Car

<h1>CONVERTING OBJECT TO DATE TIME USING PANDAS</h1>

In [ ]:
accident['Accident Date'] = pd.to_datetime(accident['Accident Date'], dayfirst=True, errors = 'coerce')

In [ ]:
accident

<h1>DISECT DATE AND CREATE NEW COLUMNS</h1>

In [ ]:
accident['Month'] = accident['Accident Date'].dt.month

In [ ]:
accident['Day'] = accident['Accident Date'].dt.day
accident['Year'] = accident['Accident Date'].dt.year
accident['DayOfWeek'] = accident['Accident Date'].dt.dayofweek

In [ ]:
accident

<h1>TREND ANALYSIS

<h2>NUMBER OF ACCIDENTS PER YEAR

In [ ]:
accident_year = accident["Year"].value_counts()

In [ ]:
accident_year

In [ ]:
accident_year.plot(kind = "bar", color="red", edgecolor="black")
plt.title("ACCIDENTS PER YEAR")
plt.xlabel("YEAR")
plt.ylabel("NUMBER OF ACCIDENTS")
plt.gcf().set_size_inches(12,8)
plt.show()

<p> BASE ON THE FINDING WE SEE THAT THE YEAR WITH THE MOST NUMBER OF ACCIDENTS IS THE YEAR 2019

<h1>NUMBER OF ACCIDENTS PER MONTH

In [ ]:
accident_month = accident["Month"].value_counts().sort_index()
accident_month

In [ ]:
accident_month.plot(kind = "bar", color="red", edgecolor="black")
plt.title("ACCIDENTS PER MONTH")
plt.xlabel("MONTHS")
plt.ylabel("NUMBER OF ACCIDENTS")
plt.gcf().set_size_inches(12,8)
plt.show()

<p> BASE ON THE FINDING WE SEE THAT THE MONTH WITH THE MOST NUMBER OF ACCIDENTS IS THE MONTH OF NOVEMBER

<H1>NUMBER OF ACCIDENTS PER DAY OF WEEK

In [ ]:
accident_dow = accident["DayOfWeek"].value_counts().sort_index()

In [ ]:
accident_dow

In [ ]:
accident_dow.plot(kind = "bar", color="red", edgecolor="black")
plt.title("ACCIDENTS PER DAY OF A WEEK")
plt.xlabel("DAYOFWEEK")
plt.ylabel("NUMBER OF ACCIDENTS")
plt.gcf().set_size_inches(12,8)
plt.show()

<p> BASE ON THE FINDING WE SEE THAT THE DAY OF WEEK WITH THE MOST NUMBER OF ACCIDENTS IS THURSDAY

<H1>NUMBER OF ACCIDENTS PER MONTH UNDER LIGHT CONDITIONS

In [ ]:
accident_month_light = accident.groupby(['Month', "Light_Conditions"]).size()

In [ ]:
accident_month_light

In [ ]:
accident_month_light = accident.groupby(['Month', "Light_Conditions"]).size().unstack()

In [ ]:
accident_month_light

In [ ]:
accident_month_light.plot(kind = "bar", edgecolor="black", stacked=True)
plt.title("ACCIDENTS PER MONTH UNDER LIGHT CCONDITIONS")
plt.xlabel("MONTHS")
plt.ylabel("LIGHT CONDITIONS")
plt.gcf().set_size_inches(12,8)
plt.legend(title="LIGHT CONDITION", loc='upper left', bbox_to_anchor=(1.05, 1))
plt.show()

In [ ]:
accident_dayofweek = accident.groupby(['DayOfWeek', "Road_Surface_Conditions"]).size().unstack()
accident_dayofweek

<h1>NUMBER OF ACCIDENTS PER DAY OF WEEK UNDER ROAD SURFACE CONDITIONS

In [ ]:
accident_dayofweek.plot(kind = "bar", edgecolor="black", stacked=True)
plt.title("ACCIDENTS PER DAY OF WEEK UNDER ROAD SURFACE CONDITION")
plt.xlabel("DAY OF WEEK")
plt.ylabel("ROAD SURFACE CONDITIONS")
plt.gcf().set_size_inches(12,8)
plt.legend(title="ROAD SURFACE CONDITION", loc='upper left', bbox_to_anchor=(1.05, 1))
plt.show()

<H1>NUMBER OF ACCIDENT SEVERITY UNDER URBAN AND RURAL AREAS

In [ ]:
accident_urban_rural = accident.groupby(['Accident_Severity', "Urban_or_Rural_Area"]).size().unstack()
accident_urban_rural

In [ ]:
accident_urban_rural.plot(kind = "bar", edgecolor="black", stacked=True)
plt.title("ACCIDENTS SEVERITY IN URBAN AND RURAL AREAS")
plt.xlabel("ACCIDENT SEVERITY")
plt.ylabel("URBAN AND RURAL AREA")
plt.gcf().set_size_inches(12,8)
plt.legend(title="ACCIDENT SEVERITY", loc='upper left', bbox_to_anchor=(1.05, 1))
plt.show()

<H1>NUMBER OF ACCIDENTS PER YEAR UNDER WEATHER CONDITONS

In [ ]:
accident_year_weather = accident.groupby(['Year', "Weather_Conditions"]).size().unstack()
accident_year_weather

In [ ]:
accident_year_weather.plot(kind = "bar", edgecolor="black", stacked=True)
plt.title("ACCIDENTS PER YEAR UNDER WEATHER CONDITIONS")
plt.xlabel("YEAR")
plt.ylabel("WEATHER CONDITIONS")
plt.gcf().set_size_inches(12,8)
plt.legend(title="WEATHER CONDITIONS", loc='upper left', bbox_to_anchor=(1.05, 1))
plt.show()

In [ ]:
num_casualties = accident.groupby(['Accident_Severity', "Number_of_Casualties"]).size().unstack()
num_casualties

In [ ]:
num_casualties.plot(kind = "bar", edgecolor="black", stacked=True)
plt.title("NUMBER OF CASUALTIES IN ROAD SURFACE CONDITION")
plt.xlabel("ROAD SURFACE CONDITION")
plt.ylabel("NUMBER OF CASUALTIES")
plt.gcf().set_size_inches(12,8)
plt.legend(title="ROAD SURFACE CONDITION", loc='upper left', bbox_to_anchor=(1.05, 1))
plt.show()